/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrediccionesRouteImport } from './routes/predicciones'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as AnalizadorRouteImport } from './routes/analizador'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalizadorRouteImport } from './routes/api/analizador'

const PrediccionesRoute = PrediccionesRouteImport.update({
  id: '/predicciones',
  path: '/predicciones',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalizadorRoute = AnalizadorRouteImport.update({
  id: '/analizador',
  path: '/analizador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalizadorRoute = ApiAnalizadorRouteImport.update({
  id: '/api/analizador',
  path: '/api/analizador',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analizador': typeof AnalizadorRoute
  '/mapa': typeof MapaRoute
  '/predicciones': typeof PrediccionesRoute
  '/api/analizador': typeof ApiAnalizadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analizador': typeof AnalizadorRoute
  '/mapa': typeof MapaRoute
  '/predicciones': typeof PrediccionesRoute
  '/api/analizador': typeof ApiAnalizadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analizador': typeof AnalizadorRoute
  '/mapa': typeof MapaRoute
  '/predicciones': typeof PrediccionesRoute
  '/api/analizador': typeof ApiAnalizadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analizador' | '/mapa' | '/predicciones' | '/api/analizador'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analizador' | '/mapa' | '/predicciones' | '/api/analizador'
  id:
    | '__root__'
    | '/'
    | '/analizador'
    | '/mapa'
    | '/predicciones'
    | '/api/analizador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalizadorRoute: typeof AnalizadorRoute
  MapaRoute: typeof MapaRoute
  PrediccionesRoute: typeof PrediccionesRoute
  ApiAnalizadorRoute: typeof ApiAnalizadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/predicciones': {
      id: '/predicciones'
      path: '/predicciones'
      fullPath: '/predicciones'
      preLoaderRoute: typeof PrediccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analizador': {
      id: '/analizador'
      path: '/analizador'
      fullPath: '/analizador'
      preLoaderRoute: typeof AnalizadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analizador': {
      id: '/api/analizador'
      path: '/api/analizador'
      fullPath: '/api/analizador'
      preLoaderRoute: typeof ApiAnalizadorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalizadorRoute: AnalizadorRoute,
  MapaRoute: MapaRoute,
  PrediccionesRoute: PrediccionesRoute,
  ApiAnalizadorRoute: ApiAnalizadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
